name: 'Build and release'

on: workflow_dispatch

jobs:
  build:
    name: 'Build the project'
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          ref: master
      - name: 'Set up Java'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: 'Build shadow jar'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./build/libs/*-all.jar
      - name: 'export version number'
        id: tag
        run: ./gradlew properties -q | grep "version:" | awk '{ print "::set-output name=tag::"$2 }'

  release-content:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download Artifacts'
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./*
          tag_name: ${{needs.build.outputs.tag-name}}
          name: version v${{needs.build.outputs.tag-name}}